name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir-version: ["1.13.2"]
        otp-version: ["24.2"]

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - name: Install Mix Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check format
        run: mix format --check-formatted
      
      - name: Run Tests
        run: mix test
